### ISSUE TITLE
Tracking S231P public review comments

### ISSUE THREAD

**Issue by anandkp92** [lbl-srg/obc#143]
- [x] #147
- [x] How to distinguish between CDL blocks and Modelica models? (add this to the specification)
- [x] Sequence names include package names? e.g: <S231P:CXF.Reals.Add> a S231P:ElementaryBlock . (add this to specification)
- [ ] #160
- [x] Add support for `replaceable` in CDL: https://github.com/lbl-srg/obc/pull/146 **Done and in Word document, 10/30/24**
- [x] The `enumeration` must be defined, such as for `ZeroTime` and for the PID controller. **mwetter: Reported by email, 10/30/24**

**Comment by anandkp92** [comment]
- [x] how to handle final class_modification (eg: in [this](https://github.com/lbl-srg/modelica-json/blob/issue214_cxf/test/FromModelica/CustomPWithLimiter.mo) example, how do we handle `gain(final k = k)`?
- [x] how to handle class modifications that are not part of the standard? (eg: in [this](https://github.com/lbl-srg/modelica-json/blob/issue214_cxf/test/FromModelica/TestEvaluation_2.mo) sequence, how do we handle `hys(final uLow=uLow, uHigh=uHigh)`
- [x] How to handle conditions for assignment? eg: [here] (https://github.com/lbl-srg/modelica-json/blob/issue214_cxf/test/FromModelica/RemovableInputs.mo)

**Comment by mwetter** [comment]
- [x] Consider changing `TrueHoldWithReset` to `TrueHold`: https://github.com/lbl-srg/modelica-buildings/issues/3689
*done*

**Comment by JayHuLBL** [comment]
In the section `7.5 Elementary block`:
- [x] Every block should have the icon.
- [x] The icons' color are not consistent. Block like `Add` exists in both `Reals` and `Integers` packages, but the icon color is blue (indicating it is a block in the `Reals` package).
- [x] In the documentation when there is a line change, it is possible that one word might be cut-off.
- [x] In the description, it should use the font `Courier New` for the variable names.
- [x] Functions should be reformatted.
- [x] Some hyperlink should be removed, like in the description of the block `Reals.Sin`.
- [x] There are`Switch` blocks in `CDL.Logical` and `CDL.Integers`, and also `CDL.Reals` **This corrected in Word**
- [x] It's necessary to redraw some figures, as some figures are too big (`TrueHoldWithReset`), or too small (`Latch`).
- [x] Differentiate `Enthalpy` and `SpecificEnthalpy`.
- [x] `OnCounter` block should be in the `Integers` package. **mwetter: Reported by email, 10/30/24**
- [x] Blocks in the `Sources` package should be the sub package of `Reals`, `Integers`, and `Logical`.
- [x] In CDL, there are `Buildings.Controls.OBC.CDL.Constants` and `Buildings.Controls.OBC.CDL.Types`. Where should this enumeration and the constants be introduced? **mwetter: Reported by email, 10/30/24**
- [x] Typo in 7.5.34.1, `CDL.Reals.Sort`, description of the output `y`: `Outpur of sorted inouts`

**Comment by mwetter** [comment]
- [x] For the staging rotation of the heat pump plants, a sort block was needed that also outputs the index. This is implemented in https://github.com/lbl-srg/modelica-buildings/blob/27afa7c54d7b2ee3820ed1b7400c0e8ee3bd5361/Buildings/Templates/Plants/Controls/Utilities/SortWithIndices.mo
and similar to `CDL.Reals.Sort` except for the additional output. We should propose to change the CDL block accordingly. Proposed to be added (email sent to Paul on 4/18/24) **mwetter: Reported again by email, 10/30/24**
- [x] Make sure `CDL.Logical.Latch` has documentation updated as in https://github.com/lbl-srg/modelica-buildings/pull/3800/files#diff-6fe286a5bd9201123e0b7af359ef7ac0a0dc5874445f519315dedf9fb191d551R3 **mwetter: Reported by email, 10/30/24**

**Comment by anandkp92** [comment]
- [x] add following specification: ensure that parameters have one of default 
```parameter k 
annotation (__cdl(default=0))
```
or a value binding (`parameter k = 0`) so that we can evaluate expressions. 

**Edit mwetter, 10/30/24**: Based on last weeks discussion this is not needed: If modelica-json evaluates expressions but there is a parameter with no binding, then this expression should be removed. If modelica-json is invoked in a way that retains expressions, then it works for expressions that have parameters without a binding.

**Comment by anandkp92** [comment]
- [x] update CXF section to include how to represent extension blocks

**Comment by anandkp92** [comment]
- [x] move section 7.2 data types for elementary blocks to sec 6 (describe use of analog type in CXF)
- [x] how to handle Reals/Integers -> analogs (in CXF) and back? IF we start from CDL, and we change Reals into Analog, we can track "this analog was originally a real". But if we start from a tool that only does Analog, then we'll need a instance-level tracking to change it back into real/integers. Do we need to change CDL.Reals.Add -> CDL(or CXF).Analog.Add?

**Comment by JayHuLBL** [comment]
@anandkp92 Can you also check if the issues you raised earlier can be marked as done?
